name: Deploy TML to ThoughtSpot

on:
  push:
    branches:
      - main
    paths:
      - '**.tml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy TML files to ThoughtSpot
      uses: thoughtspot/thoughtspot-tools@main
      with:
        host: https://ps-internal.thoughtspot.cloud
        username: ${{ secrets.TS_USERNAME }}
        password: ${{ secrets.TS_PASSWORD }}
        import_path: .
